### ISSUE TITLE
Consider Scala

### ISSUE THREAD

**Issue by btc** [teamdandelion/ecosim#8]
I forgot that Scala can utilize all of Java's concurrency primitives:

http://twitter.github.io/scala_school/concurrency.html

plus can keep the gradle build system

http://www.gradle.org/docs/current/userguide/scala_plugin.html

plus functional programming

https://www.coursera.org/course/progfun

**Comment by teamdandelion** [comment]
This seems like a fun option.

Heads up, on vacation next week and super busy wrapping up some work this
week. Maybe I'll review some scala over the next few days.
